(##define-module-alias github.com/alvatar/base base)
(##define-module-alias github.com/alvatar/sdl2 sdl2)
(##define-module-alias github.com/alvatar/gles2 gles2)
(##define-module-alias github.com/alvatar/ffi-utils ffi-utils)
(##define-module-alias github.com/alvatar/math math)
