#ifdef ___LINKER_INFO
; File: "render.c", produced by Gambit v4.9.3
(
409003
(C)
"render"
("render")
("gambit" "_match" "srfi/28" "srfi/69" "base" "base/alist" "base/functional" "base/functional/combinator" "base/memoization" "gles2" "ffi-utils" "sdl2" "sdl2/ttf" "math/matrix" "math/vector2" "core")
(("render"))
(
"##type-5"
"##type-5-polyline-type"
"##type-6-tree-node-type"
"##type-7-text-type"
"*->GLuint"
"*gl-perspective-matrix*"
"->"
"GL_ARRAY_BUFFER"
"GL_BGRA_EXT"
"GL_FALSE"
"GL_RGBA"
"GL_TEXTURE_2D"
"GL_UNSIGNED_BYTE"
"SDL_Surface-pixels"
"_match"
"base"
"base/alist"
"base/functional"
"base/functional/combinator"
"base/memoization"
"box2d"
"child-id"
"color"
"content"
"core"
"data"
"default-layer"
"dimensions"
"dirty?"
"element"
"else"
"f32vector-length"
"ffi-utils"
"fields"
"first"
"flags"
"font"
"gambit"
"glBindBuffer"
"glDrawArrays"
"glGetUniformLocation"
"glTexImage2D"
"glUniform1i"
"glUniformMatrix4fv"
"gles2"
"height"
"id"
"key"
"last"
"lines"
"math/matrix"
"math/vector2"
"matrix"
"name"
"next"
"node"
"num-points"
"parent"
"points"
"polyline"
"polylines-sublayer"
"previous"
"program-id"
"render"
"render-element"
"render-layer"
"sdl2"
"sdl2/ttf"
"size"
"srfi/28"
"srfi/69"
"style"
"sublayer"
"super"
"text"
"texts-sublayer"
"texture"
"texture-2d"
"texture-height"
"texture-surf*"
"texture-width"
"top-left"
"type"
"vbo"
"vertex-object"
"vertex-object-vbo"
"vertex-object-vertices"
"vertices"
"vo"
"width"
)
(
":box2d"
":color"
":content"
":font"
"box2d"
"color"
"content"
"elements"
"font"
"group"
"id"
"objects"
"points"
"polyline"
"ref"
"root"
"style"
"text"
)
(
"##type-2-box2d"
"##type-2-render-layer"
"##type-2-sublayer"
"##type-2-vertex-object"
"##type-3-font"
"##type-4-render-element"
"##type-4-texture"
"render#"
"render#*base-matrix*"
"render#*fonts*"
"render#*gl-base-matrix*"
"render#*gl-perspective-matrix*"
"render#*perspective-matrix*"
"render#*programs*"
"render#*render-layers*"
"render#*render-tree*"
"render#*scaling-factor*"
"render#*screen-height*"
"render#*translation-vector2*"
"render#box2d-dimensions"
"render#box2d-top-left"
"render#color->SDL_Color"
"render#f32vector->gl-buffer"
"render#font-data"
"render#fonts:shutdown"
"render#gl-create-program"
"render#gl-create-shader"
"render#graph->scene-tree"
"render#make-box2d"
"render#make-node"
"render#make-polyline"
"render#make-render-layer"
"render#make-text"
"render#node-child-id"
"render#node-child-id-set!"
"render#node-element"
"render#node-element-set!"
"render#node-parent"
"render#node-render-element"
"render#node-render-element-set!"
"render#node-type"
"render#perspective-matrix-update!"
"render#polyline-dirty?"
"render#polyline-dirty?-set!"
"render#polyline-num-points"
"render#polyline-points"
"render#polyline-points-set!"
"render#polyline-style-set!"
"render#polyline-vbo"
"render#polyline.refresh-vbo!"
"render#polyline.render"
"render#programs:init"
"render#render-element-next"
"render#render-element-next-set!"
"render#render-element-node"
"render#render-element-previous"
"render#render-element-previous-set!"
"render#render-element-sublayer"
"render#render-element.add!"
"render#render-element.remove!"
"render#render-layer-polylines-sublayer"
"render#render-layer-texts-sublayer"
"render#render-layer.add-element!"
"render#render-layer.sublayer-for-each"
"render#render-layers.render"
"render#renderer:update-view!"
"render#scene-tree->scene-layers"
"render#sdl-surface->gl-texture"
"render#sublayer-first"
"render#sublayer-first-set!"
"render#sublayer-last"
"render#sublayer-last-set!"
"render#text-box2d"
"render#text-box2d-set!"
"render#text-color"
"render#text-color-set!"
"render#text-content"
"render#text-content-set!"
"render#text-dirty?"
"render#text-dirty?-set!"
"render#text-font"
"render#text-font-set!"
"render#text-texture"
"render#text-texture-set!"
"render#text-vertex-object"
"render#text-vertex-object-set!"
"render#text.refresh!"
"render#text.render"
"render#vector-filter"
"render#vector-find"
"render#vector-swap!"
"render#vertex-object-vbo"
"render#vertex-object-vbo-set!"
"render#vertex-object-vertices"
"render#vertex-object-vertices-set!"
"render#vertex-object.refresh!/internal"
"render#vertex-object.render"
"render#with-gl-program"
"render#with-polyline-render-state"
"render#with-text-render-state/aux"
)
(
"render#*debug-texts*"
"render#*screen-width*"
"render#SDL_Color->color"
"render#box2d-bottom-right"
"render#box2d-copy"
"render#box2d-dimensions-set"
"render#box2d-dimensions-set!"
"render#box2d-top-left-set"
"render#box2d-top-left-set!"
"render#box2d?"
"render#error-log"
"render#font-copy"
"render#font-data-set"
"render#font-data-set!"
"render#font-name"
"render#font-name-set"
"render#font-name-set!"
"render#font-size"
"render#font-size-set"
"render#font-size-set!"
"render#font?"
"render#fonts:init"
"render#fonts:install"
"render#fonts:uninstall"
"render#fonts:uninstall-by-name"
"render#load-text-file"
"render#make-font"
"render#make-node/internal"
"render#make-polyline/internal"
"render#make-render-element"
"render#make-render-layer/internal"
"render#make-render-layers"
"render#make-sublayer"
"render#make-sublayer/internal"
"render#make-text/internal"
"render#make-texture/internal"
"render#make-vertex-object"
"render#make-vertex-object/empty"
"render#make-vertex-object/internal"
"render#node-child-id-set"
"render#node-copy"
"render#node-element-set"
"render#node-id"
"render#node-id-set"
"render#node-id-set!"
"render#node-parent-set"
"render#node-parent-set!"
"render#node-render-element-set"
"render#node-type-set"
"render#node-type-set!"
"render#node?"
"render#polyline-copy"
"render#polyline-dirty?-set"
"render#polyline-num-points-set"
"render#polyline-num-points-set!"
"render#polyline-points-set"
"render#polyline-style"
"render#polyline-style-set"
"render#polyline-vbo-set"
"render#polyline-vbo-set!"
"render#polyline.update!"
"render#polyline?"
"render#programs:shutdown"
"render#render-element-copy"
"render#render-element-next-set"
"render#render-element-node-set"
"render#render-element-node-set!"
"render#render-element-previous-set"
"render#render-element-sublayer-set"
"render#render-element-sublayer-set!"
"render#render-element?"
"render#render-layer-copy"
"render#render-layer-polylines-sublayer-set"
"render#render-layer-polylines-sublayer-set!"
"render#render-layer-texts-sublayer-set"
"render#render-layer-texts-sublayer-set!"
"render#render-layer?"
"render#render-layers.clear!"
"render#render-layers.for-each"
"render#render-layers.get"
"render#renderer:init"
"render#renderer:load-scene!"
"render#renderer:render"
"render#renderer:scale-view!"
"render#renderer:shutdown"
"render#renderer:translate-view!"
"render#scene-tree.add-node!"
"render#scene-tree.alter-node!"
"render#scene-tree.filter-children"
"render#scene-tree.find-child"
"render#scene-tree.remove-node!"
"render#sublayer-copy"
"render#sublayer-first-set"
"render#sublayer-last-set"
"render#sublayer?"
"render#text-box2d-set"
"render#text-color-set"
"render#text-content-set"
"render#text-copy"
"render#text-dirty?-set"
"render#text-font-set"
"render#text-texture-set"
"render#text-vertex-object-set"
"render#text.update!"
"render#text?"
"render#texture-copy"
"render#texture-height"
"render#texture-height-set"
"render#texture-height-set!"
"render#texture-id"
"render#texture-id-set"
"render#texture-id-set!"
"render#texture-key"
"render#texture-key-set"
"render#texture-key-set!"
"render#texture-vertices-rect"
"render#texture-width"
"render#texture-width-set"
"render#texture-width-set!"
"render#texture?"
"render#vertex-object-copy"
"render#vertex-object-vbo-set"
"render#vertex-object-vertices-set"
"render#vertex-object.update!"
"render#vertex-object?"
"render#with-text-overlay-render-state"
"render#with-text-render-state"
)
(
"##call-with-values"
"##car"
"##cdr"
"##direct-structure-ref"
"##direct-structure-set"
"##direct-structure-set!"
"##eq?"
"##error"
"##not"
"##null?"
"##pair?"
"##string->uninterned-symbol"
"##structure"
"##structure-copy"
"##type-type"
"*"
"+"
"-"
"/"
"<"
"="
"apply"
"assq"
"base/alist#get"
"base/alist#get+"
"base/functional/combinator#compose"
"base/memoization#memoize"
"cadr"
"car"
"cdr"
"cons"
"core#color-a"
"core#color-b"
"core#color-g"
"core#color-r"
"core#make-color"
"core#uuid-v4"
"current-input-port"
"current-time"
"display"
"error"
"exact->inexact"
"f32vector"
"f32vector-length"
"f32vector-set!"
"ffi-utils#*->string"
"ffi-utils#integer->void*"
"for-each"
"fx+"
"gles2#*->GLint"
"gles2#*->GLuint"
"gles2#GL_ARRAY_BUFFER"
"gles2#GL_BGRA_EXT"
"gles2#GL_BLEND"
"gles2#GL_CLAMP_TO_EDGE"
"gles2#GL_COLOR_BUFFER_BIT"
"gles2#GL_COMPILE_STATUS"
"gles2#GL_DEPTH_TEST"
"gles2#GL_FALSE"
"gles2#GL_FLOAT"
"gles2#GL_FRAGMENT_SHADER"
"gles2#GL_INFO_LOG_LENGTH"
"gles2#GL_LINE_STRIP"
"gles2#GL_LINK_STATUS"
"gles2#GL_MULTISAMPLE_EXT"
"gles2#GL_NEAREST"
"gles2#GL_NEVER"
"gles2#GL_NO_ERROR"
"gles2#GL_ONE_MINUS_SRC_ALPHA"
"gles2#GL_RGBA"
"gles2#GL_SRC_ALPHA"
"gles2#GL_STREAM_DRAW"
"gles2#GL_TEXTURE0"
"gles2#GL_TEXTURE_2D"
"gles2#GL_TEXTURE_MAG_FILTER"
"gles2#GL_TEXTURE_MIN_FILTER"
"gles2#GL_TEXTURE_WRAP_S"
"gles2#GL_TEXTURE_WRAP_T"
"gles2#GL_TRIANGLES"
"gles2#GL_UNSIGNED_BYTE"
"gles2#GL_VERTEX_SHADER"
"gles2#GLfloat-size"
"gles2#alloc-GLchar*"
"gles2#alloc-GLint*"
"gles2#alloc-GLuint*"
"gles2#f32vector->GLfloat*"
"gles2#glActiveTexture"
"gles2#glAttachShader"
"gles2#glBindAttribLocation"
"gles2#glBindBuffer"
"gles2#glBindTexture"
"gles2#glBlendFunc"
"gles2#glBufferData"
"gles2#glClear"
"gles2#glClearColor"
"gles2#glCompileShader"
"gles2#glCreateProgram"
"gles2#glCreateShader"
"gles2#glDeleteBuffers"
"gles2#glDeleteProgram"
"gles2#glDeleteTextures"
"gles2#glDepthFunc"
"gles2#glDetachShader"
"gles2#glDisable"
"gles2#glDrawArrays"
"gles2#glEnable"
"gles2#glEnableVertexAttribArray"
"gles2#glGenBuffers"
"gles2#glGenTextures"
"gles2#glGetError"
"gles2#glGetProgramInfoLog"
"gles2#glGetProgramiv"
"gles2#glGetShaderInfoLog"
"gles2#glGetShaderiv"
"gles2#glGetUniformLocation"
"gles2#glLinkProgram"
"gles2#glShaderSource"
"gles2#glTexImage2D"
"gles2#glTexParameteri"
"gles2#glUniform1i"
"gles2#glUniformMatrix4fv"
"gles2#glUseProgram"
"gles2#glVertexAttribPointer"
"gles2#matrix->GLfloat*"
"identity"
"length"
"list"
"list->vector"
"make-f32vector"
"make-table"
"make-vector"
"map"
"math/matrix#make-scaling-matrix"
"math/matrix#make-translation-matrix"
"math/matrix#matrix*"
"math/matrix#matrix.map"
"math/vector2#make-vector2"
"math/vector2#vector2*scalar"
"math/vector2#vector2+"
"math/vector2#vector2-x"
"math/vector2#vector2-y"
"memq"
"not"
"null?"
"object->string"
"println"
"raise"
"read-line"
"render#box2d"
"render#color"
"render#content"
"render#font"
"render#polyline.refresh!"
"render#render-element"
"sdl2#*->SDL_Color"
"sdl2#SDL_Color-a"
"sdl2#SDL_Color-a-set!"
"sdl2#SDL_Color-b"
"sdl2#SDL_Color-b-set!"
"sdl2#SDL_Color-g"
"sdl2#SDL_Color-g-set!"
"sdl2#SDL_Color-r"
"sdl2#SDL_Color-r-set!"
"sdl2#SDL_FreeSurface"
"sdl2#SDL_Surface-h"
"sdl2#SDL_Surface-pixels"
"sdl2#SDL_Surface-w"
"sdl2#alloc-SDL_Color"
"sdl2/ttf#TTF_CloseFont"
"sdl2/ttf#TTF_Init"
"sdl2/ttf#TTF_OpenFont"
"sdl2/ttf#TTF_Quit"
"sdl2/ttf#TTF_RenderUTF8_Blended"
"srfi/28#format"
"srfi/69#hash-table-ref"
"srfi/69#hash-table-update!/default"
"srfi/69#hash-table-walk"
"srfi/69#make-hash-table"
"string-append"
"string=?"
"table-for-each"
"table-ref"
"table-set!"
"time->seconds"
"values"
"vector"
"vector-append"
"vector-length"
"vector-ref"
"vector-set!"
"vector-shrink!"
"with-input-from-file"
)
( #|*/"*/"meta-info|#
) #|*/"*/"meta-info|#
)
#else
#define ___VERSION 409003
#define ___MODULE_NAME "render"
#define ___LINKER_ID ___LNK_render_2e_o1
#define ___MH_PROC ___H_render
#define ___SCRIPT_LINE 0
#define ___SYMCOUNT 90
#define ___KEYCOUNT 18
#define ___GLOCOUNT 419
#define ___SUPCOUNT 227
#define ___CNSCOUNT 55
#define ___SUBCOUNT 71
#define ___LBLCOUNT 2033
#define ___OFDCOUNT 9
#define ___MODDESCR ___REF_SUB(68)
#include "gambit.h"

___NEED_SYM(___S__23__23_type_2d_5)
___NEED_SYM(___S__23__23_type_2d_5_2d_polyline_2d_type)
___NEED_SYM(___S__23__23_type_2d_6_2d_tree_2d_node_2d_type)
___NEED_SYM(___S__23__23_type_2d_7_2d_text_2d_type)
___NEED_SYM(___S__2a__2d__3e_GLuint)
___NEED_SYM(___S__2a_gl_2d_perspective_2d_matrix_2a_)
___NEED_SYM(___S__2d__3e_)
___NEED_SYM(___S_GL__ARRAY__BUFFER)
___NEED_SYM(___S_GL__BGRA__EXT)
___NEED_SYM(___S_GL__FALSE)
___NEED_SYM(___S_GL__RGBA)
___NEED_SYM(___S_GL__TEXTURE__2D)
___NEED_SYM(___S_GL__UNSIGNED__BYTE)
___NEED_SYM(___S_SDL__Surface_2d_pixels)
___NEED_SYM(___S___match)
___NEED_SYM(___S_base)
___NEED_SYM(___S_base_2f_alist)
___NEED_SYM(___S_base_2f_functional)
___NEED_SYM(___S_base_2f_functional_2f_combinator)
___NEED_SYM(___S_base_2f_memoization)
___NEED_SYM(___S_box2d)
___NEED_SYM(___S_child_2d_id)
___NEED_SYM(___S_color)
___NEED_SYM(___S_content)
___NEED_SYM(___S_core)
___NEED_SYM(___S_data)
___NEED_SYM(___S_default_2d_layer)
___NEED_SYM(___S_dimensions)
___NEED_SYM(___S_dirty_3f_)
___NEED_SYM(___S_element)
___NEED_SYM(___S_else)
___NEED_SYM(___S_f32vector_2d_length)
___NEED_SYM(___S_ffi_2d_utils)
___NEED_SYM(___S_fields)
___NEED_SYM(___S_first)
___NEED_SYM(___S_flags)
___NEED_SYM(___S_font)
___NEED_SYM(___S_gambit)
___NEED_SYM(___S_glBindBuffer)
___NEED_SYM(___S_glDrawArrays)
___NEED_SYM(___S_glGetUniformLocation)
___NEED_SYM(___S_glTexImage2D)
___NEED_SYM(___S_glUniform1i)
___NEED_SYM(___S_glUniformMatrix4fv)
___NEED_SYM(___S_gles2)
___NEED_SYM(___S_height)
___NEED_SYM(___S_id)
___NEED_SYM(___S_key)
___NEED_SYM(___S_last)
___NEED_SYM(___S_lines)
___NEED_SYM(___S_math_2f_matrix)
___NEED_SYM(___S_math_2f_vector2)
___NEED_SYM(___S_matrix)
___NEED_SYM(___S_name)
___NEED_SYM(___S_next)
___NEED_SYM(___S_node)
___NEED_SYM(___S_num_2d_points)
___NEED_SYM(___S_parent)
___NEED_SYM(___S_points)
___NEED_SYM(___S_polyline)
___NEED_SYM(___S_polylines_2d_sublayer)
___NEED_SYM(___S_previous)
___NEED_SYM(___S_program_2d_id)
___NEED_SYM(___S_render)
___NEED_SYM(___S_render_2d_element)
___NEED_SYM(___S_render_2d_layer)
___NEED_SYM(___S_sdl2)
___NEED_SYM(___S_sdl2_2f_ttf)
___NEED_SYM(___S_size)
___NEED_SYM(___S_srfi_2f_28)
___NEED_SYM(___S_srfi_2f_69)
___NEED_SYM(___S_style)
___NEED_SYM(___S_sublayer)
___NEED_SYM(___S_super)
___NEED_SYM(___S_text)
___NEED_SYM(___S_texts_2d_sublayer)
___NEED_SYM(___S_texture)
___NEED_SYM(___S_texture_2d_2d)
___NEED_SYM(___S_texture_2d_height)
___NEED_SYM(___S_texture_2d_surf_2a_)
___NEED_SYM(___S_texture_2d_width)
___NEED_SYM(___S_top_2d_left)
___NEED_SYM(___S_type)
___NEED_SYM(___S_vbo)
___NEED_SYM(___S_vertex_2d_object)
___NEED_SYM(___S_vertex_2d_object_2d_vbo)
___NEED_SYM(___S_vertex_2d_object_2d_vertices)
___NEED_SYM(___S_vertices)
___NEED_SYM(___S_vo)
___NEED_SYM(___S_width)

___NEED_KEY(___K__3a_box2d)
___NEED_KEY(___K__3a_color)
___NEED_KEY(___K__3a_content)
___NEED_KEY(___K__3a_font)
___NEED_KEY(___K_box2d)
___NEED_KEY(___K_color)
___NEED_KEY(___K_content)
___NEED_KEY(___K_elements)
___NEED_KEY(___K_font)
___NEED_KEY(___K_group)
___NEED_KEY(___K_id)
___NEED_KEY(___K_objects)
___NEED_KEY(___K_points)
___NEED_KEY(___K_polyline)
___NEED_KEY(___K_ref)
___NEED_KEY(___K_root)
___NEED_KEY(___K_style)
___NEED_KEY(___K_text)

___NEED_GLO(___G__23__23_call_2d_with_2d_values)
___NEED_GLO(___G__23__23_car)
___NEED_GLO(___G__23__23_cdr)
___NEED_GLO(___G__23__23_direct_2d_structure_2d_ref)
___NEED_GLO(___G__23__23_direct_2d_structure_2d_set)
___NEED_GLO(___G__23__23_direct_2d_structure_2d_set_21_)
___NEED_GLO(___G__23__23_eq_3f_)
___NEED_GLO(___G__23__23_error)
___NEED_GLO(___G__23__23_not)
___NEED_GLO(___G__23__23_null_3f_)
___NEED_GLO(___G__23__23_pair_3f_)
___NEED_GLO(___G__23__23_string_2d__3e_uninterned_2d_symbol)
___NEED_GLO(___G__23__23_structure)
___NEED_GLO(___G__23__23_structure_2d_copy)
___NEED_GLO(___G__23__23_type_2d_2_2d_box2d)
___NEED_GLO(___G__23__23_type_2d_2_2d_render_2d_layer)
___NEED_GLO(___G__23__23_type_2d_2_2d_sublayer)
___NEED_GLO(___G__23__23_type_2d_2_2d_vertex_2d_object)
___NEED_GLO(___G__23__23_type_2d_3_2d_font)
___NEED_GLO(___G__23__23_type_2d_4_2d_render_2d_element)
___NEED_GLO(___G__23__23_type_2d_4_2d_texture)
___NEED_GLO(___G__23__23_type_2d_type)
___NEED_GLO(___G__2a_)
___NEED_GLO(___G__2b_)
___NEED_GLO(___G__2d_)
___NEED_GLO(___G__2f_)
___NEED_GLO(___G__3c_)
___NEED_GLO(___G__3d_)
___NEED_GLO(___G_apply)
___NEED_GLO(___G_assq)
___NEED_GLO(___G_base_2f_alist_23_get)
___NEED_GLO(___G_base_2f_alist_23_get_2b_)
___NEED_GLO(___G_base_2f_functional_2f_combinator_23_compose)
___NEED_GLO(___G_base_2f_memoization_23_memoize)
___NEED_GLO(___G_cadr)
___NEED_GLO(___G_car)
___NEED_GLO(___G_cdr)
___NEED_GLO(___G_cons)
___NEED_GLO(___G_core_23_color_2d_a)
___NEED_GLO(___G_core_23_color_2d_b)
___NEED_GLO(___G_core_23_color_2d_g)
___NEED_GLO(___G_core_23_color_2d_r)
___NEED_GLO(___G_core_23_make_2d_color)
___NEED_GLO(___G_core_23_uuid_2d_v4)
___NEED_GLO(___G_current_2d_input_2d_port)
___NEED_GLO(___G_current_2d_time)
___NEED_GLO(___G_display)
___NEED_GLO(___G_error)
___NEED_GLO(___G_exact_2d__3e_inexact)
___NEED_GLO(___G_f32vector)
___NEED_GLO(___G_f32vector_2d_length)
___NEED_GLO(___G_f32vector_2d_set_21_)
___NEED_GLO(___G_ffi_2d_utils_23__2a__2d__3e_string)
___NEED_GLO(___G_ffi_2d_utils_23_integer_2d__3e_void_2a_)
___NEED_GLO(___G_for_2d_each)
___NEED_GLO(___G_fx_2b_)
___NEED_GLO(___G_gles2_23__2a__2d__3e_GLint)
___NEED_GLO(___G_gles2_23__2a__2d__3e_GLuint)
___NEED_GLO(___G_gles2_23_GL__ARRAY__BUFFER)
___NEED_GLO(___G_gles2_23_GL__BGRA__EXT)
___NEED_GLO(___G_gles2_23_GL__BLEND)
___NEED_GLO(___G_gles2_23_GL__CLAMP__TO__EDGE)
___NEED_GLO(___G_gles2_23_GL__COLOR__BUFFER__BIT)
___NEED_GLO(___G_gles2_23_GL__COMPILE__STATUS)
___NEED_GLO(___G_gles2_23_GL__DEPTH__TEST)
___NEED_GLO(___G_gles2_23_GL__FALSE)
___NEED_GLO(___G_gles2_23_GL__FLOAT)
___NEED_GLO(___G_gles2_23_GL__FRAGMENT__SHADER)
___NEED_GLO(___G_gles2_23_GL__INFO__LOG__LENGTH)
___NEED_GLO(___G_gles2_23_GL__LINE__STRIP)
___NEED_GLO(___G_gles2_23_GL__LINK__STATUS)
___NEED_GLO(___G_gles2_23_GL__MULTISAMPLE__EXT)
___NEED_GLO(___G_gles2_23_GL__NEAREST)
___NEED_GLO(___G_gles2_23_GL__NEVER)
___NEED_GLO(___G_gles2_23_GL__NO__ERROR)
___NEED_GLO(___G_gles2_23_GL__ONE__MINUS__SRC__ALPHA)
___NEED_GLO(___G_gles2_23_GL__RGBA)
___NEED_GLO(___G_gles2_23_GL__SRC__ALPHA)
___NEED_GLO(___G_gles2_23_GL__STREAM__DRAW)
___NEED_GLO(___G_gles2_23_GL__TEXTURE0)
___NEED_GLO(___G_gles2_23_GL__TEXTURE__2D)
___NEED_GLO(___G_gles2_23_GL__TEXTURE__MAG__FILTER)
___NEED_GLO(___G_gles2_23_GL__TEXTURE__MIN__FILTER)
___NEED_GLO(___G_gles2_23_GL__TEXTURE__WRAP__S)
___NEED_GLO(___G_gles2_23_GL__TEXTURE__WRAP__T)
___NEED_GLO(___G_gles2_23_GL__TRIANGLES)
___NEED_GLO(___G_gles2_23_GL__UNSIGNED__BYTE)
___NEED_GLO(___G_gles2_23_GL__VERTEX__SHADER)
___NEED_GLO(___G_gles2_23_GLfloat_2d_size)
___NEED_GLO(___G_gles2_23_alloc_2d_GLchar_2a_)
___NEED_GLO(___G_gles2_23_alloc_2d_GLint_2a_)
___NEED_GLO(___G_gles2_23_alloc_2d_GLuint_2a_)
___NEED_GLO(___G_gles2_23_f32vector_2d__3e_GLfloat_2a_)
___NEED_GLO(___G_gles2_23_glActiveTexture)
___NEED_GLO(___G_gles2_23_glAttachShader)
___NEED_GLO(___G_gles2_23_glBindAttribLocation)
___NEED_GLO(___G_gles2_23_glBindBuffer)
___NEED_GLO(___G_gles2_23_glBindTexture)
___NEED_GLO(___G_gles2_23_glBlendFunc)
___NEED_GLO(___G_gles2_23_glBufferData)
___NEED_GLO(___G_gles2_23_glClear)
___NEED_GLO(___G_gles2_23_glClearColor)
___NEED_GLO(___G_gles2_23_glCompileShader)
___NEED_GLO(___G_gles2_23_glCreateProgram)
___NEED_GLO(___G_gles2_23_glCreateShader)
___NEED_GLO(___G_gles2_23_glDeleteBuffers)
___NEED_GLO(___G_gles2_23_glDeleteProgram)
___NEED_GLO(___G_gles2_23_glDeleteTextures)
___NEED_GLO(___G_gles2_23_glDepthFunc)
___NEED_GLO(___G_gles2_23_glDetachShader)
___NEED_GLO(___G_gles2_23_glDisable)
___NEED_GLO(___G_gles2_23_glDrawArrays)
___NEED_GLO(___G_gles2_23_glEnable)
___NEED_GLO(___G_gles2_23_glEnableVertexAttribArray)
___NEED_GLO(___G_gles2_23_glGenBuffers)
___NEED_GLO(___G_gles2_23_glGenTextures)
___NEED_GLO(___G_gles2_23_glGetError)
___NEED_GLO(___G_gles2_23_glGetProgramInfoLog)
___NEED_GLO(___G_gles2_23_glGetProgramiv)
___NEED_GLO(___G_gles2_23_glGetShaderInfoLog)
___NEED_GLO(___G_gles2_23_glGetShaderiv)
___NEED_GLO(___G_gles2_23_glGetUniformLocation)
___NEED_GLO(___G_gles2_23_glLinkProgram)
___NEED_GLO(___G_gles2_23_glShaderSource)
___NEED_GLO(___G_gles2_23_glTexImage2D)
___NEED_GLO(___G_gles2_23_glTexParameteri)
___NEED_GLO(___G_gles2_23_glUniform1i)
___NEED_GLO(___G_gles2_23_glUniformMatrix4fv)
___NEED_GLO(___G_gles2_23_glUseProgram)
___NEED_GLO(___G_gles2_23_glVertexAttribPointer)
___NEED_GLO(___G_gles2_23_matrix_2d__3e_GLfloat_2a_)
___NEED_GLO(___G_identity)
___NEED_GLO(___G_length)
___NEED_GLO(___G_list)
___NEED_GLO(___G_list_2d__3e_vector)
___NEED_GLO(___G_make_2d_f32vector)
___NEED_GLO(___G_make_2d_table)
___NEED_GLO(___G_make_2d_vector)
___NEED_GLO(___G_map)
___NEED_GLO(___G_math_2f_matrix_23_make_2d_scaling_2d_matrix)
___NEED_GLO(___G_math_2f_matrix_23_make_2d_translation_2d_matrix)
___NEED_GLO(___G_math_2f_matrix_23_matrix_2a_)
___NEED_GLO(___G_math_2f_matrix_23_matrix_2e_map)
___NEED_GLO(___G_math_2f_vector2_23_make_2d_vector2)
___NEED_GLO(___G_math_2f_vector2_23_vector2_2a_scalar)
___NEED_GLO(___G_math_2f_vector2_23_vector2_2b_)
___NEED_GLO(___G_math_2f_vector2_23_vector2_2d_x)
___NEED_GLO(___G_math_2f_vector2_23_vector2_2d_y)
___NEED_GLO(___G_memq)
___NEED_GLO(___G_not)
___NEED_GLO(___G_null_3f_)
___NEED_GLO(___G_object_2d__3e_string)
___NEED_GLO(___G_println)
___NEED_GLO(___G_raise)
___NEED_GLO(___G_read_2d_line)
___NEED_GLO(___G_render_23_)
___NEED_GLO(___G_render_23__2a_base_2d_matrix_2a_)
___NEED_GLO(___G_render_23__2a_debug_2d_texts_2a_)
___NEED_GLO(___G_render_23__2a_fonts_2a_)
___NEED_GLO(___G_render_23__2a_gl_2d_base_2d_matrix_2a_)
___NEED_GLO(___G_render_23__2a_gl_2d_perspective_2d_matrix_2a_)
___NEED_GLO(___G_render_23__2a_perspective_2d_matrix_2a_)
___NEED_GLO(___G_render_23__2a_programs_2a_)
___NEED_GLO(___G_render_23__2a_render_2d_layers_2a_)
___NEED_GLO(___G_render_23__2a_render_2d_tree_2a_)
___NEED_GLO(___G_render_23__2a_scaling_2d_factor_2a_)
___NEED_GLO(___G_render_23__2a_screen_2d_height_2a_)
___NEED_GLO(___G_render_23__2a_screen_2d_width_2a_)
___NEED_GLO(___G_render_23__2a_translation_2d_vector2_2a_)
___NEED_GLO(___G_render_23_SDL__Color_2d__3e_color)
___NEED_GLO(___G_render_23_box2d)
___NEED_GLO(___G_render_23_box2d_2d_bottom_2d_right)
___NEED_GLO(___G_render_23_box2d_2d_copy)
___NEED_GLO(___G_render_23_box2d_2d_dimensions)
___NEED_GLO(___G_render_23_box2d_2d_dimensions_2d_set)
___NEED_GLO(___G_render_23_box2d_2d_dimensions_2d_set_21_)
___NEED_GLO(___G_render_23_box2d_2d_top_2d_left)
___NEED_GLO(___G_render_23_box2d_2d_top_2d_left_2d_set)
___NEED_GLO(___G_render_23_box2d_2d_top_2d_left_2d_set_21_)
___NEED_GLO(___G_render_23_box2d_3f_)
___NEED_GLO(___G_render_23_color)
___NEED_GLO(___G_render_23_color_2d__3e_SDL__Color)
___NEED_GLO(___G_render_23_content)
___NEED_GLO(___G_render_23_error_2d_log)
___NEED_GLO(___G_render_23_f32vector_2d__3e_gl_2d_buffer)
___NEED_GLO(___G_render_23_font)
___NEED_GLO(___G_render_23_font_2d_copy)
___NEED_GLO(___G_render_23_font_2d_data)
___NEED_GLO(___G_render_23_font_2d_data_2d_set)
___NEED_GLO(___G_render_23_font_2d_data_2d_set_21_)
___NEED_GLO(___G_render_23_font_2d_name)
___NEED_GLO(___G_render_23_font_2d_name_2d_set)
___NEED_GLO(___G_render_23_font_2d_name_2d_set_21_)
___NEED_GLO(___G_render_23_font_2d_size)
___NEED_GLO(___G_render_23_font_2d_size_2d_set)
___NEED_GLO(___G_render_23_font_2d_size_2d_set_21_)
___NEED_GLO(___G_render_23_font_3f_)
___NEED_GLO(___G_render_23_fonts_3a_init)
___NEED_GLO(___G_render_23_fonts_3a_install)
___NEED_GLO(___G_render_23_fonts_3a_shutdown)
___NEED_GLO(___G_render_23_fonts_3a_uninstall)
___NEED_GLO(___G_render_23_fonts_3a_uninstall_2d_by_2d_name)
___NEED_GLO(___G_render_23_gl_2d_create_2d_program)
___NEED_GLO(___G_render_23_gl_2d_create_2d_shader)
___NEED_GLO(___G_render_23_graph_2d__3e_scene_2d_tree)
___NEED_GLO(___G_render_23_load_2d_text_2d_file)
___NEED_GLO(___G_render_23_make_2d_box2d)
___NEED_GLO(___G_render_23_make_2d_font)
___NEED_GLO(___G_render_23_make_2d_node)
___NEED_GLO(___G_render_23_make_2d_node_2f_internal)
___NEED_GLO(___G_render_23_make_2d_polyline)
___NEED_GLO(___G_render_23_make_2d_polyline_2f_internal)
___NEED_GLO(___G_render_23_make_2d_render_2d_element)
___NEED_GLO(___G_render_23_make_2d_render_2d_layer)
___NEED_GLO(___G_render_23_make_2d_render_2d_layer_2f_internal)
___NEED_GLO(___G_render_23_make_2d_render_2d_layers)
___NEED_GLO(___G_render_23_make_2d_sublayer)
___NEED_GLO(___G_render_23_make_2d_sublayer_2f_internal)
___NEED_GLO(___G_render_23_make_2d_text)
___NEED_GLO(___G_render_23_make_2d_text_2f_internal)
___NEED_GLO(___G_render_23_make_2d_texture_2f_internal)
___NEED_GLO(___G_render_23_make_2d_vertex_2d_object)
___NEED_GLO(___G_render_23_make_2d_vertex_2d_object_2f_empty)
___NEED_GLO(___G_render_23_make_2d_vertex_2d_object_2f_internal)
___NEED_GLO(___G_render_23_node_2d_child_2d_id)
___NEED_GLO(___G_render_23_node_2d_child_2d_id_2d_set)
___NEED_GLO(___G_render_23_node_2d_child_2d_id_2d_set_21_)
___NEED_GLO(___G_render_23_node_2d_copy)
___NEED_GLO(___G_render_23_node_2d_element)
___NEED_GLO(___G_render_23_node_2d_element_2d_set)
___NEED_GLO(___G_render_23_node_2d_element_2d_set_21_)
___NEED_GLO(___G_render_23_node_2d_id)
___NEED_GLO(___G_render_23_node_2d_id_2d_set)
___NEED_GLO(___G_render_23_node_2d_id_2d_set_21_)
___NEED_GLO(___G_render_23_node_2d_parent)
___NEED_GLO(___G_render_23_node_2d_parent_2d_set)
___NEED_GLO(___G_render_23_node_2d_parent_2d_set_21_)
___NEED_GLO(___G_render_23_node_2d_render_2d_element)
___NEED_GLO(___G_render_23_node_2d_render_2d_element_2d_set)
___NEED_GLO(___G_render_23_node_2d_render_2d_element_2d_set_21_)
___NEED_GLO(___G_render_23_node_2d_type)
___NEED_GLO(___G_render_23_node_2d_type_2d_set)
___NEED_GLO(___G_render_23_node_2d_type_2d_set_21_)
___NEED_GLO(___G_render_23_node_3f_)
___NEED_GLO(___G_render_23_perspective_2d_matrix_2d_update_21_)
___NEED_GLO(___G_render_23_polyline_2d_copy)
___NEED_GLO(___G_render_23_polyline_2d_dirty_3f_)
___NEED_GLO(___G_render_23_polyline_2d_dirty_3f__2d_set)
___NEED_GLO(___G_render_23_polyline_2d_dirty_3f__2d_set_21_)
___NEED_GLO(___G_render_23_polyline_2d_num_2d_points)
___NEED_GLO(___G_render_23_polyline_2d_num_2d_points_2d_set)
___NEED_GLO(___G_render_23_polyline_2d_num_2d_points_2d_set_21_)
___NEED_GLO(___G_render_23_polyline_2d_points)
___NEED_GLO(___G_render_23_polyline_2d_points_2d_set)
___NEED_GLO(___G_render_23_polyline_2d_points_2d_set_21_)
___NEED_GLO(___G_render_23_polyline_2d_style)
___NEED_GLO(___G_render_23_polyline_2d_style_2d_set)
___NEED_GLO(___G_render_23_polyline_2d_style_2d_set_21_)
___NEED_GLO(___G_render_23_polyline_2d_vbo)
___NEED_GLO(___G_render_23_polyline_2d_vbo_2d_set)
___NEED_GLO(___G_render_23_polyline_2d_vbo_2d_set_21_)
___NEED_GLO(___G_render_23_polyline_2e_refresh_21_)
___NEED_GLO(___G_render_23_polyline_2e_refresh_2d_vbo_21_)
___NEED_GLO(___G_render_23_polyline_2e_render)
___NEED_GLO(___G_render_23_polyline_2e_update_21_)
___NEED_GLO(___G_render_23_polyline_3f_)
___NEED_GLO(___G_render_23_programs_3a_init)
___NEED_GLO(___G_render_23_programs_3a_shutdown)
___NEED_GLO(___G_render_23_render_2d_element)
___NEED_GLO(___G_render_23_render_2d_element_2d_copy)
___NEED_GLO(___G_render_23_render_2d_element_2d_next)
___NEED_GLO(___G_render_23_render_2d_element_2d_next_2d_set)
___NEED_GLO(___G_render_23_render_2d_element_2d_next_2d_set_21_)
___NEED_GLO(___G_render_23_render_2d_element_2d_node)
___NEED_GLO(___G_render_23_render_2d_element_2d_node_2d_set)
___NEED_GLO(___G_render_23_render_2d_element_2d_node_2d_set_21_)
___NEED_GLO(___G_render_23_render_2d_element_2d_previous)
___NEED_GLO(___G_render_23_render_2d_element_2d_previous_2d_set)
___NEED_GLO(___G_render_23_render_2d_element_2d_previous_2d_set_21_)
___NEED_GLO(___G_render_23_render_2d_element_2d_sublayer)
___NEED_GLO(___G_render_23_render_2d_element_2d_sublayer_2d_set)
___NEED_GLO(___G_render_23_render_2d_element_2d_sublayer_2d_set_21_)
___NEED_GLO(___G_render_23_render_2d_element_2e_add_21_)
___NEED_GLO(___G_render_23_render_2d_element_2e_remove_21_)
___NEED_GLO(___G_render_23_render_2d_element_3f_)
___NEED_GLO(___G_render_23_render_2d_layer_2d_copy)
___NEED_GLO(___G_render_23_render_2d_layer_2d_polylines_2d_sublayer)
___NEED_GLO(___G_render_23_render_2d_layer_2d_polylines_2d_sublayer_2d_set)
___NEED_GLO(___G_render_23_render_2d_layer_2d_polylines_2d_sublayer_2d_set_21_)
___NEED_GLO(___G_render_23_render_2d_layer_2d_texts_2d_sublayer)
___NEED_GLO(___G_render_23_render_2d_layer_2d_texts_2d_sublayer_2d_set)
___NEED_GLO(___G_render_23_render_2d_layer_2d_texts_2d_sublayer_2d_set_21_)
___NEED_GLO(___G_render_23_render_2d_layer_2e_add_2d_element_21_)
___NEED_GLO(___G_render_23_render_2d_layer_2e_sublayer_2d_for_2d_each)
___NEED_GLO(___G_render_23_render_2d_layer_3f_)
___NEED_GLO(___G_render_23_render_2d_layers_2e_clear_21_)
___NEED_GLO(___G_render_23_render_2d_layers_2e_for_2d_each)
___NEED_GLO(___G_render_23_render_2d_layers_2e_get)
___NEED_GLO(___G_render_23_render_2d_layers_2e_render)
___NEED_GLO(___G_render_23_renderer_3a_init)
___NEED_GLO(___G_render_23_renderer_3a_load_2d_scene_21_)
___NEED_GLO(___G_render_23_renderer_3a_render)
___NEED_GLO(___G_render_23_renderer_3a_scale_2d_view_21_)
___NEED_GLO(___G_render_23_renderer_3a_shutdown)
___NEED_GLO(___G_render_23_renderer_3a_translate_2d_view_21_)
___NEED_GLO(___G_render_23_renderer_3a_update_2d_view_21_)
___NEED_GLO(___G_render_23_scene_2d_tree_2d__3e_scene_2d_layers)
___NEED_GLO(___G_render_23_scene_2d_tree_2e_add_2d_node_21_)
___NEED_GLO(___G_render_23_scene_2d_tree_2e_alter_2d_node_21_)
___NEED_GLO(___G_render_23_scene_2d_tree_2e_filter_2d_children)
___NEED_GLO(___G_render_23_scene_2d_tree_2e_find_2d_child)
___NEED_GLO(___G_render_23_scene_2d_tree_2e_remove_2d_node_21_)
___NEED_GLO(___G_render_23_sdl_2d_surface_2d__3e_gl_2d_texture)
___NEED_GLO(___G_render_23_sublayer_2d_copy)
___NEED_GLO(___G_render_23_sublayer_2d_first)
___NEED_GLO(___G_render_23_sublayer_2d_first_2d_set)
___NEED_GLO(___G_render_23_sublayer_2d_first_2d_set_21_)
___NEED_GLO(___G_render_23_sublayer_2d_last)
___NEED_GLO(___G_render_23_sublayer_2d_last_2d_set)
___NEED_GLO(___G_render_23_sublayer_2d_last_2d_set_21_)
___NEED_GLO(___G_render_23_sublayer_3f_)
___NEED_GLO(___G_render_23_text_2d_box2d)
___NEED_GLO(___G_render_23_text_2d_box2d_2d_set)
___NEED_GLO(___G_render_23_text_2d_box2d_2d_set_21_)
___NEED_GLO(___G_render_23_text_2d_color)
___NEED_GLO(___G_render_23_text_2d_color_2d_set)
___NEED_GLO(___G_render_23_text_2d_color_2d_set_21_)
___NEED_GLO(___G_render_23_text_2d_content)
___NEED_GLO(___G_render_23_text_2d_content_2d_set)
___NEED_GLO(___G_render_23_text_2d_content_2d_set_21_)
___NEED_GLO(___G_render_23_text_2d_copy)
___NEED_GLO(___G_render_23_text_2d_dirty_3f_)
___NEED_GLO(___G_render_23_text_2d_dirty_3f__2d_set)
___NEED_GLO(___G_render_23_text_2d_dirty_3f__2d_set_21_)
___NEED_GLO(___G_render_23_text_2d_font)
___NEED_GLO(___G_render_23_text_2d_font_2d_set)
___NEED_GLO(___G_render_23_text_2d_font_2d_set_21_)
___NEED_GLO(___G_render_23_text_2d_texture)
___NEED_GLO(___G_render_23_text_2d_texture_2d_set)
___NEED_GLO(___G_render_23_text_2d_texture_2d_set_21_)
___NEED_GLO(___G_render_23_text_2d_vertex_2d_object)
___NEED_GLO(___G_render_23_text_2d_vertex_2d_object_2d_set)
___NEED_GLO(___G_render_23_text_2d_vertex_2d_object_2d_set_21_)
___NEED_GLO(___G_render_23_text_2e_refresh_21_)
___NEED_GLO(___G_render_23_text_2e_render)
___NEED_GLO(___G_render_23_text_2e_update_21_)
___NEED_GLO(___G_render_23_text_3f_)
___NEED_GLO(___G_render_23_texture_2d_copy)
___NEED_GLO(___G_render_23_texture_2d_height)
___NEED_GLO(___G_render_23_texture_2d_height_2d_set)
___NEED_GLO(___G_render_23_texture_2d_height_2d_set_21_)
___NEED_GLO(___G_render_23_texture_2d_id)
___NEED_GLO(___G_render_23_texture_2d_id_2d_set)
___NEED_GLO(___G_render_23_texture_2d_id_2d_set_21_)
___NEED_GLO(___G_render_23_texture_2d_key)
___NEED_GLO(___G_render_23_texture_2d_key_2d_set)
___NEED_GLO(___G_render_23_texture_2d_key_2d_set_21_)
___NEED_GLO(___G_render_23_texture_2d_vertices_2d_rect)
___NEED_GLO(___G_render_23_texture_2d_width)
___NEED_GLO(___G_render_23_texture_2d_width_2d_set)
___NEED_GLO(___G_render_23_texture_2d_width_2d_set_21_)
___NEED_GLO(___G_render_23_texture_3f_)
___NEED_GLO(___G_render_23_vector_2d_filter)
___NEED_GLO(___G_render_23_vector_2d_find)
___NEED_GLO(___G_render_23_vector_2d_swap_21_)
___NEED_GLO(___G_render_23_vertex_2d_object_2d_copy)
___NEED_GLO(___G_render_23_vertex_2d_object_2d_vbo)
___NEED_GLO(___G_render_23_vertex_2d_object_2d_vbo_2d_set)
___NEED_GLO(___G_render_23_vertex_2d_object_2d_vbo_2d_set_21_)
___NEED_GLO(___G_render_23_vertex_2d_object_2d_vertices)
___NEED_GLO(___G_render_23_vertex_2d_object_2d_vertices_2d_set)
___NEED_GLO(___G_render_23_vertex_2d_object_2d_vertices_2d_set_21_)
___NEED_GLO(___G_render_23_vertex_2d_object_2e_refresh_21__2f_internal)
___NEED_GLO(___G_render_23_vertex_2d_object_2e_render)
___NEED_GLO(___G_render_23_vertex_2d_object_2e_update_21_)
___NEED_GLO(___G_render_23_vertex_2d_object_3f_)
___NEED_GLO(___G_render_23_with_2d_gl_2d_program)
___NEED_GLO(___G_render_23_with_2d_polyline_2d_render_2d_state)
___NEED_GLO(___G_render_23_with_2d_text_2d_overlay_2d_render_2d_state)
___NEED_GLO(___G_render_23_with_2d_text_2d_render_2d_state)
___NEED_GLO(___G_render_23_with_2d_text_2d_render_2d_state_2f_aux)
___NEED_GLO(___G_sdl2_23__2a__2d__3e_SDL__Color)
___NEED_GLO(___G_sdl2_23_SDL__Color_2d_a)
___NEED_GLO(___G_sdl2_23_SDL__Color_2d_a_2d_set_21_)
___NEED_GLO(___G_sdl2_23_SDL__Color_2d_b)
___NEED_GLO(___G_sdl2_23_SDL__Color_2d_b_2d_set_21_)
___NEED_GLO(___G_sdl2_23_SDL__Color_2d_g)
___NEED_GLO(___G_sdl2_23_SDL__Color_2d_g_2d_set_21_)
___NEED_GLO(___G_sdl2_23_SDL__Color_2d_r)
___NEED_GLO(___G_sdl2_23_SDL__Color_2d_r_2d_set_21_)
___NEED_GLO(___G_sdl2_23_SDL__FreeSurface)
___NEED_GLO(___G_sdl2_23_SDL__Surface_2d_h)
___NEED_GLO(___G_sdl2_23_SDL__Surface_2d_pixels)
___NEED_GLO(___G_sdl2_23_SDL__Surface_2d_w)
___NEED_GLO(___G_sdl2_23_alloc_2d_SDL__Color)
___NEED_GLO(___G_sdl2_2f_ttf_23_TTF__CloseFont)
___NEED_GLO(___G_sdl2_2f_ttf_23_TTF__Init)
___NEED_GLO(___G_sdl2_2f_ttf_23_TTF__OpenFont)
___NEED_GLO(___G_sdl2_2f_ttf_23_TTF__Quit)
___NEED_GLO(___G_sdl2_2f_ttf_23_TTF__RenderUTF8__Blended)
___NEED_GLO(___G_srfi_2f_28_23_format)
___NEED_GLO(___G_srfi_2f_69_23_hash_2d_table_2d_ref)
___NEED_GLO(___G_srfi_2f_69_23_hash_2d_table_2d_update_21__2f_default)
___NEED_GLO(___G_srfi_2f_69_23_hash_2d_table_2d_walk)
___NEED_GLO(___G_srfi_2f_69_23_make_2d_hash_2d_table)
___NEED_GLO(___G_string_2d_append)
___NEED_GLO(___G_string_3d__3f_)
___NEED_GLO(___G_table_2d_for_2d_each)
___NEED_GLO(___G_table_2d_ref)
___NEED_GLO(___G_table_2d_set_21_)
___NEED_GLO(___G_time_2d__3e_seconds)
___NEED_GLO(___G_values)
___NEED_GLO(___G_vector)
___NEED_GLO(___G_vector_2d_append)
___NEED_GLO(___G_vector_2d_length)
___NEED_GLO(___G_vector_2d_ref)
___NEED_GLO(___G_vector_2d_set_21_)
___NEED_GLO(___G_vector_2d_shrink_21_)
___NEED_GLO(___G_with_2d_input_2d_from_2d_file)

___BEGIN_SYM
___DEF_SYM(0,___S__23__23_type_2d_5,"##type-5")
___DEF_SYM(1,___S__23__23_type_2d_5_2d_polyline_2d_type,"##type-5-polyline-type")
___DEF_SYM(2,___S__23__23_type_2d_6_2d_tree_2d_node_2d_type,"##type-6-tree-node-type")
___DEF_SYM(3,___S__23__23_type_2d_7_2d_text_2d_type,"##type-7-text-type")
___DEF_SYM(4,___S__2a__2d__3e_GLuint,"*->GLuint")
___DEF_SYM(5,___S__2a_gl_2d_perspective_2d_matrix_2a_,"*gl-perspective-matrix*")
___DEF_SYM(6,___S__2d__3e_,"->")
___DEF_SYM(7,___S_GL__ARRAY__BUFFER,"GL_ARRAY_BUFFER")
___DEF_SYM(8,___S_GL__BGRA__EXT,"GL_BGRA_EXT")
___DEF_SYM(9,___S_GL__FALSE,"GL_FALSE")
___DEF_SYM(10,___S_GL__RGBA,"GL_RGBA")
___DEF_SYM(11,___S_GL__TEXTURE__2D,"GL_TEXTURE_2D")
___DEF_SYM(12,___S_GL__UNSIGNED__BYTE,"GL_UNSIGNED_BYTE")
___DEF_SYM(13,___S_SDL__Surface_2d_pixels,"SDL_Surface-pixels")
___DEF_SYM(14,___S___match,"_match")
___DEF_SYM(15,___S_base,"base")
___DEF_SYM(16,___S_base_2f_alist,"base/alist")
___DEF_SYM(17,___S_base_2f_functional,"base/functional")
___DEF_SYM(18,___S_base_2f_functional_2f_combinator,"base/functional/combinator")
___DEF_SYM(19,___S_base_2f_memoization,"base/memoization")
___DEF_SYM(20,___S_box2d,"box2d")
___DEF_SYM(21,___S_child_2d_id,"child-id")
___DEF_SYM(22,___S_color,"color")
___DEF_SYM(23,___S_content,"content")
___DEF_SYM(24,___S_core,"core")
___DEF_SYM(25,___S_data,"data")
___DEF_SYM(26,___S_default_2d_layer,"default-layer")
___DEF_SYM(27,___S_dimensions,"dimensions")
___DEF_SYM(28,___S_dirty_3f_,"dirty?")
___DEF_SYM(29,___S_element,"element")
___DEF_SYM(30,___S_else,"else")
___DEF_SYM(31,___S_f32vector_2d_length,"f32vector-length")
___DEF_SYM(32,___S_ffi_2d_utils,"ffi-utils")
___DEF_SYM(33,___S_fields,"fields")
___DEF_SYM(34,___S_first,"first")
___DEF_SYM(35,___S_flags,"flags")
___DEF_SYM(36,___S_font,"font")
___DEF_SYM(37,___S_gambit,"gambit")
___DEF_SYM(38,___S_glBindBuffer,"glBindBuffer")
___DEF_SYM(39,___S_glDrawArrays,"glDrawArrays")
___DEF_SYM(40,___S_glGetUniformLocation,"glGetUniformLocation")
___DEF_SYM(41,___S_glTexImage2D,"glTexImage2D")
___DEF_SYM(42,___S_glUniform1i,"glUniform1i")
___DEF_SYM(43,___S_glUniformMatrix4fv,"glUniformMatrix4fv")
___DEF_SYM(44,___S_gles2,"gles2")
___DEF_SYM(45,___S_height,"height")
___DEF_SYM(46,___S_id,"id")
___DEF_SYM(47,___S_key,"key")
___DEF_SYM(48,___S_last,"last")
___DEF_SYM(49,___S_lines,"lines")
___DEF_SYM(50,___S_math_2f_matrix,"math/matrix")
___DEF_SYM(51,___S_math_2f_vector2,"math/vector2")
___DEF_SYM(52,___S_matrix,"matrix")
___DEF_SYM(53,___S_name,"name")
___DEF_SYM(54,___S_next,"next")
___DEF_SYM(55,___S_node,"node")
___DEF_SYM(56,___S_num_2d_points,"num-points")
___DEF_SYM(57,___S_parent,"parent")
___DEF_SYM(58,___S_points,"points")
___DEF_SYM(59,___S_polyline,"polyline")
___DEF_SYM(60,___S_polylines_2d_sublayer,"polylines-sublayer")
___DEF_SYM(61,___S_previous,"previous")
___DEF_SYM(62,___S_program_2d_id,"program-id")
___DEF_SYM(63,___S_render,"render")
___DEF_SYM(64,___S_render_2d_element,"render-element")
___DEF_SYM(65,___S_render_2d_layer,"render-layer")
___DEF_SYM(66,___S_sdl2,"sdl2")
___DEF_SYM(67,___S_sdl2_2f_ttf,"sdl2/ttf")
___DEF_SYM(68,___S_size,"size")
___DEF_SYM(69,___S_srfi_2f_28,"srfi/28")
___DEF_SYM(70,___S_srfi_2f_69,"srfi/69")
___DEF_SYM(71,___S_style,"style")
___DEF_SYM(72,___S_sublayer,"sublayer")
___DEF_SYM(73,___S_super,"super")
___DEF_SYM(74,___S_text,"text")
___DEF_SYM(75,___S_texts_2d_sublayer,"texts-sublayer")
___DEF_SYM(76,___S_texture,"texture")
___DEF_SYM(77,___S_texture_2d_2d,"texture-2d")
___DEF_SYM(78,___S_texture_2d_height,"texture-height")
___DEF_SYM(79,___S_texture_2d_surf_2a_,"texture-surf*")
___DEF_SYM(80,___S_texture_2d_width,"texture-width")
___DEF_SYM(81,___S_top_2d_left,"top-left")
___DEF_SYM(82,___S_type,"type")
___DEF_SYM(83,___S_vbo,"vbo")
___DEF_SYM(84,___S_vertex_2d_object,"vertex-object")
___DEF_SYM(85,___S_vertex_2d_object_2d_vbo,"vertex-object-vbo")
___DEF_SYM(86,___S_vertex_2d_object_2d_vertices,"vertex-object-vertices")
___DEF_SYM(87,___S_vertices,"vertices")
___DEF_SYM(88,___S_vo,"vo")
___DEF_SYM(89,___S_width,"width")
___END_SYM

#define ___SYM__23__23_type_2d_5 ___SYM(0,___S__23__23_type_2d_5)
#define ___SYM__23__23_type_2d_5_2d_polyline_2d_type ___SYM(1,___S__23__23_type_2d_5_2d_polyline_2d_type)
#define ___SYM__23__23_type_2d_6_2d_tree_2d_node_2d_type ___SYM(2,___S__23__23_type_2d_6_2d_tree_2d_node_2d_type)
#define ___SYM__23__23_type_2d_7_2d_text_2d_type ___SYM(3,___S__23__23_type_2d_7_2d_text_2d_type)
#define ___SYM__2a__2d__3e_GLuint ___SYM(4,___S__2a__2d__3e_GLuint)
#define ___SYM__2a_gl_2d_perspective_2d_matrix_2a_ ___SYM(5,___S__2a_gl_2d_perspective_2d_matrix_2a_)
#define ___SYM__2d__3e_ ___SYM(6,___S__2d__3e_)
#define ___SYM_GL__ARRAY__BUFFER ___SYM(7,___S_GL__ARRAY__BUFFER)
#define ___SYM_GL__BGRA__EXT ___SYM(8,___S_GL__BGRA__EXT)
#define ___SYM_GL__FALSE ___SYM(9,___S_GL__FALSE)
#define ___SYM_GL__RGBA ___SYM(10,___S_GL__RGBA)
#define ___SYM_GL__TEXTURE__2D ___SYM(11,___S_GL__TEXTURE__2D)
#define ___SYM_GL__UNSIGNED__BYTE ___SYM(12,___S_GL__UNSIGNED__BYTE)
#define ___SYM_SDL__Surface_2d_pixels ___SYM(13,___S_SDL__Surface_2d_pixels)
#define ___SYM___match ___SYM(14,___S___match)
#define ___SYM_base ___SYM(15,___S_base)
#define ___SYM_base_2f_alist ___SYM(16,___S_base_2f_alist)
#define ___SYM_base_2f_functional ___SYM(17,___S_base_2f_functional)
#define ___SYM_base_2f_functional_2f_combinator ___SYM(18,___S_base_2f_functional_2f_combinator)
#define ___SYM_base_2f_memoization ___SYM(19,___S_base_2f_memoization)
#define ___SYM_box2d ___SYM(20,___S_box2d)
#define ___SYM_child_2d_id ___SYM(21,___S_child_2d_id)
#define ___SYM_color ___SYM(22,___S_color)
#define ___SYM_content ___SYM(23,___S_content)
#define ___SYM_core ___SYM(24,___S_core)
#define ___SYM_data ___SYM(25,___S_data)
#define ___SYM_default_2d_layer ___SYM(26,___S_default_2d_layer)
#define ___SYM_dimensions ___SYM(27,___S_dimensions)
#define ___SYM_dirty_3f_ ___SYM(28,___S_dirty_3f_)
#define ___SYM_element ___SYM(29,___S_element)
#define ___SYM_else ___SYM(30,___S_else)
#define ___SYM_f32vector_2d_length ___SYM(31,___S_f32vector_2d_length)
#define ___SYM_ffi_2d_utils ___SYM(32,___S_ffi_2d_utils)
#define ___SYM_fields ___SYM(33,___S_fields)
#define ___SYM_first ___SYM(34,___S_first)
#define ___SYM_flags ___SYM(35,___S_flags)
#define ___SYM_font ___SYM(36,___S_font)
#define ___SYM_gambit ___SYM(37,___S_gambit)
#define ___SYM_glBindBuffer ___SYM(38,___S_glBindBuffer)
#define ___SYM_glDrawArrays ___SYM(39,___S_glDrawArrays)
#define ___SYM_glGetUniformLocation ___SYM(40,___S_glGetUniformLocation)
#define ___SYM_glTexImage2D ___SYM(41,___S_glTexImage2D)
#define ___SYM_glUniform1i ___SYM(42,___S_glUniform1i)
#define ___SYM_glUniformMatrix4fv ___SYM(43,___S_glUniformMatrix4fv)
#define ___SYM_gles2 ___SYM(44,___S_gles2)
#define ___SYM_height ___SYM(45,___S_height)
#define ___SYM_id ___SYM(46,___S_id)
#define ___SYM_key ___SYM(47,___S_key)
#define ___SYM_last ___SYM(48,___S_last)
#define ___SYM_lines ___SYM(49,___S_lines)
#define ___SYM_math_2f_matrix ___SYM(50,___S_math_2f_matrix)
#define ___SYM_math_2f_vector2 ___SYM(51,___S_math_2f_vector2)
#define ___SYM_matrix ___SYM(52,___S_matrix)
#define ___SYM_name ___SYM(53,___S_name)
#define ___SYM_next ___SYM(54,___S_next)
#define ___SYM_node ___SYM(55,___S_node)
#define ___SYM_num_2d_points ___SYM(56,___S_num_2d_points)
#define ___SYM_parent ___SYM(57,___S_parent)
#define ___SYM_points ___SYM(58,___S_points)
#define ___SYM_polyline ___SYM(59,___S_polyline)
#define ___SYM_polylines_2d_sublayer ___SYM(60,___S_polylines_2d_sublayer)
#define ___SYM_previous ___SYM(61,___S_previous)
#define ___SYM_program_2d_id ___SYM(62,___S_program_2d_id)
#define ___SYM_render ___SYM(63,___S_render)
#define ___SYM_render_2d_element ___SYM(64,___S_render_2d_element)
#define ___SYM_render_2d_layer ___SYM(65,___S_render_2d_layer)
#define ___SYM_sdl2 ___SYM(66,___S_sdl2)
#define ___SYM_sdl2_2f_ttf ___SYM(67,___S_sdl2_2f_ttf)
#define ___SYM_size ___SYM(68,___S_size)
#define ___SYM_srfi_2f_28 ___SYM(69,___S_srfi_2f_28)
#define ___SYM_srfi_2f_69 ___SYM(70,___S_srfi_2f_69)
#define ___SYM_style ___SYM(71,___S_style)
#define ___SYM_sublayer ___SYM(72,___S_sublayer)
#define ___SYM_super ___SYM(73,___S_super)
#define ___SYM_text ___SYM(74,___S_text)
#define ___SYM_texts_2d_sublayer ___SYM(75,___S_texts_2d_sublayer)
#define ___SYM_texture ___SYM(76,___S_texture)
#define ___SYM_texture_2d_2d ___SYM(77,___S_texture_2d_2d)
#define ___SYM_texture_2d_height ___SYM(78,___S_texture_2d_height)
#define ___SYM_texture_2d_surf_2a_ ___SYM(79,___S_texture_2d_surf_2a_)
#define ___SYM_texture_2d_width ___SYM(80,___S_texture_2d_width)
#define ___SYM_top_2d_left ___SYM(81,___S_top_2d_left)
#define ___SYM_type ___SYM(82,___S_type)
#define ___SYM_vbo ___SYM(83,___S_vbo)
#define ___SYM_vertex_2d_object ___SYM(84,___S_vertex_2d_object)
#define ___SYM_vertex_2d_object_2d_vbo ___SYM(85,___S_vertex_2d_object_2d_vbo)
#define ___SYM_vertex_2d_object_2d_vertices ___SYM(86,___S_vertex_2d_object_2d_vertices)
#define ___SYM_vertices ___SYM(87,___S_vertices)
#define ___SYM_vo ___SYM(88,___S_vo)
#define ___SYM_width ___SYM(89,___S_width)

___BEGIN_KEY
___DEF_KEY(0,___K__3a_box2d,":box2d")
___DEF_KEY(1,___K__3a_color,":color")
___DEF_KEY(2,___K__3a_content,":content")
___DEF_KEY(3,___K__3a_font,":font")
___DEF_KEY(4,___K_box2d,"box2d")
___DEF_KEY(5,___K_color,"color")
___DEF_KEY(6,___K_content,"content")
___DEF_KEY(7,___K_elements,"elements")
___DEF_KEY(8,___K_font,"font")
___DEF_KEY(9,___K_group,"group")
___DEF_KEY(10,___K_id,"id")
___DEF_KEY(11,___K_objects,"objects")
___DEF_KEY(12,___K_points,"points")
___DEF_KEY(13,___K_polyline,"polyline")
___DEF_KEY(14,___K_ref,"ref")
___DEF_KEY(15,___K_root,"root")
___DEF_KEY(16,___K_style,"style")
___DEF_KEY(17,___K_text,"text")
___END_KEY

#define ___KEY__3a_box2d ___KEY(0,___K__3a_box2d)
#define ___KEY__3a_color ___KEY(1,___K__3a_color)
#define ___KEY__3a_content ___KEY(2,___K__3a_content)
#define ___KEY__3a_font ___KEY(3,___K__3a_font)
#define ___KEY_box2d ___KEY(4,___K_box2d)
#define ___KEY_color ___KEY(5,___K_color)
#define ___KEY_content ___KEY(6,___K_content)
#define ___KEY_elements ___KEY(7,___K_elements)
#define ___KEY_font ___KEY(8,___K_font)
#define ___KEY_group ___KEY(9,___K_group)
#define ___KEY_id ___KEY(10,___K_id)
#define ___KEY_objects ___KEY(11,___K_objects)
#define ___KEY_points ___KEY(12,___K_points)
#define ___KEY_polyline ___KEY(13,___K_polyline)
#define ___KEY_ref ___KEY(14,___K_ref)
#define ___KEY_root ___KEY(15,___K_root)
#define ___KEY_style ___KEY(16,___K_style)
#define ___KEY_text ___KEY(17,___K_text)

___BEGIN_GLO
___DEF_GLO(0,"##type-2-box2d")
___DEF_GLO(1,"##type-2-render-layer")
___DEF_GLO(2,"##type-2-sublayer")
___DEF_GLO(3,"##type-2-vertex-object")
___DEF_GLO(4,"##type-3-font")
___DEF_GLO(5,"##type-4-render-element")
___DEF_GLO(6,"##type-4-texture")
___DEF_GLO(7,"render#")
___DEF_GLO(8,"render#*base-matrix*")
___DEF_GLO(9,"render#*debug-texts*")
___DEF_GLO(10,"render#*fonts*")
___DEF_GLO(11,"render#*gl-base-matrix*")
___DEF_GLO(12,"render#*gl-perspective-matrix*")
___DEF_GLO(13,"render#*perspective-matrix*")
___DEF_GLO(14,"render#*programs*")
___DEF_GLO(15,"render#*render-layers*")
___DEF_GLO(16,"render#*render-tree*")
___DEF_GLO(17,"render#*scaling-factor*")
___DEF_GLO(18,"render#*screen-height*")
___DEF_GLO(19,"render#*screen-width*")
___DEF_GLO(20,"render#*translation-vector2*")
___DEF_GLO(21,"render#SDL_Color->color")
___DEF_GLO(22,"render#box2d-bottom-right")
___DEF_GLO(23,"render#box2d-copy")
___DEF_GLO(24,"render#box2d-dimensions")
___DEF_GLO(25,"render#box2d-dimensions-set")
___DEF_GLO(26,"render#box2d-dimensions-set!")
___DEF_GLO(27,"render#box2d-top-left")
___DEF_GLO(28,"render#box2d-top-left-set")
___DEF_GLO(29,"render#box2d-top-left-set!")
___DEF_GLO(30,"render#box2d?")
___DEF_GLO(31,"render#color->SDL_Color")
___DEF_GLO(32,"render#error-log")
___DEF_GLO(33,"render#f32vector->gl-buffer")
___DEF_GLO(34,"render#font-copy")
___DEF_GLO(35,"render#font-data")
___DEF_GLO(36,"render#font-data-set")
___DEF_GLO(37,"render#font-data-set!")
___DEF_GLO(38,"render#font-name")
___DEF_GLO(39,"render#font-name-set")
___DEF_GLO(40,"render#font-name-set!")
___DEF_GLO(41,"render#font-size")
___DEF_GLO(42,"render#font-size-set")
___DEF_GLO(43,"render#font-size-set!")
___DEF_GLO(44,"render#font?")
___DEF_GLO(45,"render#fonts:init")
___DEF_GLO(46,"render#fonts:install")
___DEF_GLO(47,"render#fonts:shutdown")
___DEF_GLO(48,"render#fonts:uninstall")
___DEF_GLO(49,"render#fonts:uninstall-by-name")
___DEF_GLO(50,"render#gl-create-program")
___DEF_GLO(51,"render#gl-create-shader")
___DEF_GLO(52,"render#graph->scene-tree")
___DEF_GLO(53,"render#load-text-file")
___DEF_GLO(54,"render#make-box2d")
___DEF_GLO(55,"render#make-font")
___DEF_GLO(56,"render#make-node")
___DEF_GLO(57,"render#make-node/internal")
___DEF_GLO(58,"render#make-polyline")
___DEF_GLO(59,"render#make-polyline/internal")
___DEF_GLO(60,"render#make-render-element")
___DEF_GLO(61,"render#make-render-layer")
___DEF_GLO(62,"render#make-render-layer/internal")

___DEF_GLO(63,"render#make-render-layers")
___DEF_GLO(64,"render#make-sublayer")
___DEF_GLO(65,"render#make-sublayer/internal")
___DEF_GLO(66,"render#make-text")
___DEF_GLO(67,"render#make-text/internal")
___DEF_GLO(68,"render#make-texture/internal")
___DEF_GLO(69,"render#make-vertex-object")
___DEF_GLO(70,"render#make-vertex-object/empty")
___DEF_GLO(71,"render#make-vertex-object/internal")

___DEF_GLO(72,"render#node-child-id")
___DEF_GLO(73,"render#node-child-id-set")
___DEF_GLO(74,"render#node-child-id-set!")
___DEF_GLO(75,"render#node-copy")
___DEF_GLO(76,"render#node-element")
___DEF_GLO(77,"render#node-element-set")
___DEF_GLO(78,"render#node-element-set!")
___DEF_GLO(79,"render#node-id")
___DEF_GLO(80,"render#node-id-set")
___DEF_GLO(81,"render#node-id-set!")
___DEF_GLO(82,"render#node-parent")
___DEF_GLO(83,"render#node-parent-set")
___DEF_GLO(84,"render#node-parent-set!")
___DEF_GLO(85,"render#node-render-element")
___DEF_GLO(86,"render#node-render-element-set")
___DEF_GLO(87,"render#node-render-element-set!")
___DEF_GLO(88,"render#node-type")
___DEF_GLO(89,"render#node-type-set")
___DEF_GLO(90,"render#node-type-set!")
___DEF_GLO(91,"render#node?")
___DEF_GLO(92,"render#perspective-matrix-update!")

___DEF_GLO(93,"render#polyline-copy")
___DEF_GLO(94,"render#polyline-dirty?")
___DEF_GLO(95,"render#polyline-dirty?-set")
___DEF_GLO(96,"render#polyline-dirty?-set!")
___DEF_GLO(97,"render#polyline-num-points")
___DEF_GLO(98,"render#polyline-num-points-set")
___DEF_GLO(99,"render#polyline-num-points-set!")
___DEF_GLO(100,"render#polyline-points")
___DEF_GLO(101,"render#polyline-points-set")
___DEF_GLO(102,"render#polyline-points-set!")
___DEF_GLO(103,"render#polyline-style")
___DEF_GLO(104,"render#polyline-style-set")
___DEF_GLO(105,"render#polyline-style-set!")
___DEF_GLO(106,"render#polyline-vbo")
___DEF_GLO(107,"render#polyline-vbo-set")
___DEF_GLO(108,"render#polyline-vbo-set!")
___DEF_GLO(109,"render#polyline.refresh-vbo!")
___DEF_GLO(110,"render#polyline.render")
___DEF_GLO(111,"render#polyline.update!")
___DEF_GLO(112,"render#polyline?")
___DEF_GLO(113,"render#programs:init")
___DEF_GLO(114,"render#programs:shutdown")
___DEF_GLO(115,"render#render-element-copy")
___DEF_GLO(116,"render#render-element-next")
___DEF_GLO(117,"render#render-element-next-set")
___DEF_GLO(118,"render#render-element-next-set!")
___DEF_GLO(119,"render#render-element-node")
___DEF_GLO(120,"render#render-element-node-set")
___DEF_GLO(121,"render#render-element-node-set!")
___DEF_GLO(122,"render#render-element-previous")
___DEF_GLO(123,"render#render-element-previous-set")

___DEF_GLO(124,"render#render-element-previous-set!")

___DEF_GLO(125,"render#render-element-sublayer")
___DEF_GLO(126,"render#render-element-sublayer-set")

___DEF_GLO(127,"render#render-element-sublayer-set!")

___DEF_GLO(128,"render#render-element.add!")
___DEF_GLO(129,"render#render-element.remove!")
___DEF_GLO(130,"render#render-element?")
___DEF_GLO(131,"render#render-layer-copy")
___DEF_GLO(132,"render#render-layer-polylines-sublayer")

___DEF_GLO(133,"render#render-layer-polylines-sublayer-set")

___DEF_GLO(134,"render#render-layer-polylines-sublayer-set!")

___DEF_GLO(135,"render#render-layer-texts-sublayer")

___DEF_GLO(136,"render#render-layer-texts-sublayer-set")

___DEF_GLO(137,"render#render-layer-texts-sublayer-set!")

___DEF_GLO(138,"render#render-layer.add-element!")
___DEF_GLO(139,"render#render-layer.sublayer-for-each")

___DEF_GLO(140,"render#render-layer?")
___DEF_GLO(141,"render#render-layers.clear!")
___DEF_GLO(142,"render#render-layers.for-each")
___DEF_GLO(143,"render#render-layers.get")
___DEF_GLO(144,"render#render-layers.render")
___DEF_GLO(145,"render#renderer:init")
___DEF_GLO(146,"render#renderer:load-scene!")
___DEF_GLO(147,"render#renderer:render")
___DEF_GLO(148,"render#renderer:scale-view!")
___DEF_GLO(149,"render#renderer:shutdown")
___DEF_GLO(150,"render#renderer:translate-view!")
___DEF_GLO(151,"render#renderer:update-view!")
___DEF_GLO(152,"render#scene-tree->scene-layers")
___DEF_GLO(153,"render#scene-tree.add-node!")
___DEF_GLO(154,"render#scene-tree.alter-node!")
___DEF_GLO(155,"render#scene-tree.filter-children")

___DEF_GLO(156,"render#scene-tree.find-child")
___DEF_GLO(157,"render#scene-tree.remove-node!")
___DEF_GLO(158,"render#sdl-surface->gl-texture")
___DEF_GLO(159,"render#sublayer-copy")
___DEF_GLO(160,"render#sublayer-first")
___DEF_GLO(161,"render#sublayer-first-set")
___DEF_GLO(162,"render#sublayer-first-set!")
___DEF_GLO(163,"render#sublayer-last")
___DEF_GLO(164,"render#sublayer-last-set")
___DEF_GLO(165,"render#sublayer-last-set!")
___DEF_GLO(166,"render#sublayer?")
___DEF_GLO(167,"render#text-box2d")
___DEF_GLO(168,"render#text-box2d-set")
___DEF_GLO(169,"render#text-box2d-set!")
___DEF_GLO(170,"render#text-color")
___DEF_GLO(171,"render#text-color-set")
___DEF_GLO(172,"render#text-color-set!")
___DEF_GLO(173,"render#text-content")
___DEF_GLO(174,"render#text-content-set")
___DEF_GLO(175,"render#text-content-set!")
___DEF_GLO(176,"render#text-copy")
___DEF_GLO(177,"render#text-dirty?")
___DEF_GLO(178,"render#text-dirty?-set")
___DEF_GLO(179,"render#text-dirty?-set!")
___DEF_GLO(180,"render#text-font")
___DEF_GLO(181,"render#text-font-set")
___DEF_GLO(182,"render#text-font-set!")
___DEF_GLO(183,"render#text-texture")
___DEF_GLO(184,"render#text-texture-set")
___DEF_GLO(185,"render#text-texture-set!")
___DEF_GLO(186,"render#text-vertex-object")
___DEF_GLO(187,"render#text-vertex-object-set")
___DEF_GLO(188,"render#text-vertex-object-set!")
___DEF_GLO(189,"render#text.refresh!")
___DEF_GLO(190,"render#text.render")
___DEF_GLO(191,"render#text.update!")
___DEF_GLO(192,"render#text?")
___DEF_GLO(193,"render#texture-copy")
___DEF_GLO(194,"render#texture-height")
___DEF_GLO(195,"render#texture-height-set")
___DEF_GLO(196,"render#texture-height-set!")
___DEF_GLO(197,"render#texture-id")
___DEF_GLO(198,"render#texture-id-set")
___DEF_GLO(199,"render#texture-id-set!")
___DEF_GLO(200,"render#texture-key")
___DEF_GLO(201,"render#texture-key-set")
___DEF_GLO(202,"render#texture-key-set!")
___DEF_GLO(203,"render#texture-vertices-rect")
___DEF_GLO(204,"render#texture-width")
___DEF_GLO(205,"render#texture-width-set")
___DEF_GLO(206,"render#texture-width-set!")
___DEF_GLO(207,"render#texture?")
___DEF_GLO(208,"render#vector-filter")
___DEF_GLO(209,"render#vector-find")
___DEF_GLO(210,"render#vector-swap!")
___DEF_GLO(211,"render#vertex-object-copy")
___DEF_GLO(212,"render#vertex-object-vbo")
___DEF_GLO(213,"render#vertex-object-vbo-set")
___DEF_GLO(214,"render#vertex-object-vbo-set!")
___DEF_GLO(215,"render#vertex-object-vertices")
___DEF_GLO(216,"render#vertex-object-vertices-set")

___DEF_GLO(217,"render#vertex-object-vertices-set!")

___DEF_GLO(218,"render#vertex-object.refresh!/internal")

___DEF_GLO(219,"render#vertex-object.render")
___DEF_GLO(220,"render#vertex-object.update!")
___DEF_GLO(221,"render#vertex-object?")
___DEF_GLO(222,"render#with-gl-program")
___DEF_GLO(223,"render#with-polyline-render-state")

___DEF_GLO(224,"render#with-text-overlay-render-state")

___DEF_GLO(225,"render#with-text-render-state")
___DEF_GLO(226,"render#with-text-render-state/aux")

___DEF_GLO(227,"##call-with-values")
___DEF_GLO(228,"##car")
___DEF_GLO(229,"##cdr")
___DEF_GLO(230,"##direct-structure-ref")
___DEF_GLO(231,"##direct-structure-set")
___DEF_GLO(232,"##direct-structure-set!")
___DEF_GLO(233,"##eq?")
___DEF_GLO(234,"##error")
___DEF_GLO(235,"##not")
___DEF_GLO(236,"##null?")
___DEF_GLO(237,"##pair?")
___DEF_GLO(238,"##string->uninterned-symbol")
___DEF_GLO(239,"##structure")
___DEF_GLO(240,"##structure-copy")
___DEF_GLO(241,"##type-type")
___DEF_GLO(242,"*")
___DEF_GLO(243,"+")
___DEF_GLO(244,"-")
___DEF_GLO(245,"/")
___DEF_GLO(246,"<")
___DEF_GLO(247,"=")
___DEF_GLO(248,"apply")
___DEF_GLO(249,"assq")
___DEF_GLO(250,"base/alist#get")
___DEF_GLO(251,"base/alist#get+")
___DEF_GLO(252,"base/functional/combinator#compose")

___DEF_GLO(253,"base/memoization#memoize")
___DEF_GLO(254,"cadr")
___DEF_GLO(255,"car")
___DEF_GLO(256,"cdr")
___DEF_GLO(257,"cons")
___DEF_GLO(258,"core#color-a")
___DEF_GLO(259,"core#color-b")
___DEF_GLO(260,"core#color-g")
___DEF_GLO(261,"core#color-r")
___DEF_GLO(262,"core#make-color")
___DEF_GLO(263,"core#uuid-v4")
___DEF_GLO(264,"current-input-port")
___DEF_GLO(265,"current-time")
___DEF_GLO(266,"display")
___DEF_GLO(267,"error")
___DEF_GLO(268,"exact->inexact")
___DEF_GLO(269,"f32vector")
___DEF_GLO(270,"f32vector-length")
___DEF_GLO(271,"f32vector-set!")
___DEF_GLO(272,"ffi-utils#*->string")
___DEF_GLO(273,"ffi-utils#integer->void*")
___DEF_GLO(274,"for-each")
___DEF_GLO(275,"fx+")
___DEF_GLO(276,"gles2#*->GLint")
___DEF_GLO(277,"gles2#*->GLuint")
___DEF_GLO(278,"gles2#GL_ARRAY_BUFFER")
___DEF_GLO(279,"gles2#GL_BGRA_EXT")
___DEF_GLO(280,"gles2#GL_BLEND")
___DEF_GLO(281,"gles2#GL_CLAMP_TO_EDGE")
___DEF_GLO(282,"gles2#GL_COLOR_BUFFER_BIT")
___DEF_GLO(283,"gles2#GL_COMPILE_STATUS")
___DEF_GLO(284,"gles2#GL_DEPTH_TEST")
___DEF_GLO(285,"gles2#GL_FALSE")
___DEF_GLO(286,"gles2#GL_FLOAT")
___DEF_GLO(287,"gles2#GL_FRAGMENT_SHADER")
___DEF_GLO(288,"gles2#GL_INFO_LOG_LENGTH")
___DEF_GLO(289,"gles2#GL_LINE_STRIP")
___DEF_GLO(290,"gles2#GL_LINK_STATUS")
___DEF_GLO(291,"gles2#GL_MULTISAMPLE_EXT")
___DEF_GLO(292,"gles2#GL_NEAREST")
___DEF_GLO(293,"gles2#GL_NEVER")
___DEF_GLO(294,"gles2#GL_NO_ERROR")
___DEF_GLO(295,"gles2#GL_ONE_MINUS_SRC_ALPHA")
___DEF_GLO(296,"gles2#GL_RGBA")
___DEF_GLO(297,"gles2#GL_SRC_ALPHA")
___DEF_GLO(298,"gles2#GL_STREAM_DRAW")
___DEF_GLO(299,"gles2#GL_TEXTURE0")
___DEF_GLO(300,"gles2#GL_TEXTURE_2D")
___DEF_GLO(301,"gles2#GL_TEXTURE_MAG_FILTER")
___DEF_GLO(302,"gles2#GL_TEXTURE_MIN_FILTER")
___DEF_GLO(303,"gles2#GL_TEXTURE_WRAP_S")
___DEF_GLO(304,"gles2#GL_TEXTURE_WRAP_T")
___DEF_GLO(305,"gles2#GL_TRIANGLES")
___DEF_GLO(306,"gles2#GL_UNSIGNED_BYTE")
___DEF_GLO(307,"gles2#GL_VERTEX_SHADER")
___DEF_GLO(308,"gles2#GLfloat-size")
___DEF_GLO(309,"gles2#alloc-GLchar*")
___DEF_GLO(310,"gles2#alloc-GLint*")
___DEF_GLO(311,"gles2#alloc-GLuint*")
___DEF_GLO(312,"gles2#f32vector->GLfloat*")
___DEF_GLO(313,"gles2#glActiveTexture")
___DEF_GLO(314,"gles2#glAttachShader")
___DEF_GLO(315,"gles2#glBindAttribLocation")
___DEF_GLO(316,"gles2#glBindBuffer")
___DEF_GLO(317,"gles2#glBindTexture")
___DEF_GLO(318,"gles2#glBlendFunc")
___DEF_GLO(319,"gles2#glBufferData")
___DEF_GLO(320,"gles2#glClear")
___DEF_GLO(321,"gles2#glClearColor")
___DEF_GLO(322,"gles2#glCompileShader")
___DEF_GLO(323,"gles2#glCreateProgram")
___DEF_GLO(324,"gles2#glCreateShader")
___DEF_GLO(325,"gles2#glDeleteBuffers")
___DEF_GLO(326,"gles2#glDeleteProgram")
___DEF_GLO(327,"gles2#glDeleteTextures")
___DEF_GLO(328,"gles2#glDepthFunc")
___DEF_GLO(329,"gles2#glDetachShader")
___DEF_GLO(330,"gles2#glDisable")
___DEF_GLO(331,"gles2#glDrawArrays")
___DEF_GLO(332,"gles2#glEnable")
___DEF_GLO(333,"gles2#glEnableVertexAttribArray")
___DEF_GLO(334,"gles2#glGenBuffers")
___DEF_GLO(335,"gles2#glGenTextures")
___DEF_GLO(336,"gles2#glGetError")
___DEF_GLO(337,"gles2#glGetProgramInfoLog")
___DEF_GLO(338,"gles2#glGetProgramiv")
___DEF_GLO(339,"gles2#glGetShaderInfoLog")
___DEF_GLO(340,"gles2#glGetShaderiv")
___DEF_GLO(341,"gles2#glGetUniformLocation")
___DEF_GLO(342,"gles2#glLinkProgram")
___DEF_GLO(343,"gles2#glShaderSource")
___DEF_GLO(344,"gles2#glTexImage2D")
___DEF_GLO(345,"gles2#glTexParameteri")
___DEF_GLO(346,"gles2#glUniform1i")
___DEF_GLO(347,"gles2#glUniformMatrix4fv")
___DEF_GLO(348,"gles2#glU